apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -dev

replicas:
  - name: cloudops-app
    count: 1

configMapGenerator:
  - name: cloudops-config
    behavior: merge

    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
