#cloud-config

package_update: true
package_upgrade: true

write_files:
  - path: /opt/install/docker.sh
    permissions: "0755"
    owner: root:root
    content: |
${docker_script}

  - path: /opt/install/k3s.sh
    permissions: "0755"
    owner: root:root
    content: |
${k3s_script}

  - path: /opt/install/helm.sh
    permissions: "0755"
    owner: root:root
    content: |
${helm_script}

runcmd:
  # Install Nginx
  - apt-get update
  - apt-get install -y nginx
  - systemctl enable nginx
  - systemctl start nginx

  # Install CloudWatch Agent
  - wget https://amazoncloudwatch-agent.s3.amazonaws.com/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
  - dpkg -i amazon-cloudwatch-agent.deb

  # Start CloudWatch Agent
  - /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c ssm:/amazon-cloudwatch-agent/config -s

  # Install Docker
  - /opt/install/docker.sh

  # Install K3s
  - /opt/install/k3s.sh

  # Install Helm
  - /opt/install/helm.sh

final_message: "Cloud-init completed successfully."
