name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # 🔥 REQUIRED for OIDC
      contents: read

    defaults:
      run:
        working-directory: terraform/environments/prod

    steps:
      
      # Checkout Code
      
      - name: Checkout code
        uses: actions/checkout@v4

      
      # Setup Terraform
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      
      # Configure AWS (OIDC)
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::116101834005:role/github-actions-terraform
          aws-region: eu-west-1

      

      
      # Terraform Init
      
      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: terraform/environments/prod

      - name: Import existing IAM Role
   run: |
    terraform import aws_iam_role.ec2_ssm_role ec2-ssm-role || echo "Already imported"

     - name: Import existing Instance Profile
  run: |
    terraform import aws_iam_instance_profile.ec2 ec2-ssm-profile || echo "Already imported"

        
      
      # Terraform Plan
      
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform/environments/prod

      
      # Terraform Apply
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/environments/prod
